server:
  port: 8080

spring:
  application:
    name: security-uaa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_security?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true #当遇到同样名字时 是否允许覆盖注册

eureka:
  client:
    register-with-eureka: true #表示是否将自己注册进EurekaServer默认为true
    fetchRegistry: true #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      #单机版
      defaultZone: http://localhost:7001/eureka #Eureka Server地址

feign:
  hystrix:
    enabled: true